# Generated by Django 3.1 on 2021-03-15 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 3, 15, 9, 22, 59, 598540, tzinfo=utc))),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
