# Generated by Django 3.1 on 2021-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
