# Generated by Django 3.1 on 2021-03-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210315_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Employees',
        ),
    ]
