# Generated by Django 3.1 on 2021-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210315_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
