# Generated by Django 3.1 on 2021-03-16 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employees_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
